DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS delivery_address;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
    id BIGINT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    phone VARCHAR(20),
    password_hash VARCHAR(100) NOT NULL,
    nickname VARCHAR(50) NOT NULL,
    gender TINYINT NOT NULL DEFAULT 0,
    avatar_url VARCHAR(255),
    status TINYINT NOT NULL DEFAULT 1,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE delivery_address (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    receiver_name VARCHAR(50) NOT NULL,
    receiver_phone VARCHAR(20) NOT NULL,
    address_detail VARCHAR(255) NOT NULL,
    address_label VARCHAR(20),
    is_default TINYINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP
);

INSERT INTO users (id, username, password_hash, nickname, status) VALUES
    (1, 'address_owner', 'unused_test_hash', '地址用户', 1),
    (2, 'address_other', 'unused_test_hash', '其他用户', 1),
    (3, 'address_disabled', 'unused_test_hash', '禁用用户', 0);

INSERT INTO delivery_address (id, user_id, receiver_name, receiver_phone, address_detail, address_label, is_default) VALUES
    (1, 1, '测试收货人', '19900000001', '一号楼', '学校', 1),
    (2, 1, '测试收货人', '19900000001', '二号楼', NULL, 0),
    (3, 1, '测试收货人', '19900000001', '三号楼', NULL, 0),
    (4, 2, '其他收货人', '19900000002', '其他地址', NULL, 1);
ALTER TABLE delivery_address ALTER COLUMN id RESTART WITH 5;
