DROP TABLE IF EXISTS order_item;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS shop;
DROP TABLE IF EXISTS merchant;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS admin_account;

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR(50) NOT NULL,
    phone VARCHAR(20) DEFAULT NULL,
    password_hash VARCHAR(100) NOT NULL,
    nickname VARCHAR(50) NOT NULL,
    gender TINYINT NOT NULL DEFAULT 0,
    avatar_url VARCHAR(255) DEFAULT NULL,
    status TINYINT NOT NULL DEFAULT 1,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_admin_test_users_username UNIQUE (username)
);

CREATE TABLE merchant (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    account VARCHAR(50) NOT NULL,
    password_hash VARCHAR(100) NOT NULL,
    merchant_name VARCHAR(100) NOT NULL,
    contact_name VARCHAR(50) NOT NULL,
    contact_phone VARCHAR(20) NOT NULL,
    status TINYINT NOT NULL DEFAULT 1,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_admin_test_merchant_account UNIQUE (account)
);

CREATE TABLE shop (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    merchant_id BIGINT NOT NULL,
    shop_name VARCHAR(100) NOT NULL,
    description VARCHAR(255) DEFAULT NULL,
    address VARCHAR(255) NOT NULL,
    image_url VARCHAR(255) DEFAULT NULL,
    start_price DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    delivery_price DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    business_status TINYINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    order_no VARCHAR(64) NOT NULL,
    user_id BIGINT NOT NULL,
    shop_id BIGINT NOT NULL,
    address_id BIGINT DEFAULT NULL,
    receiver_name VARCHAR(50) NOT NULL,
    receiver_phone VARCHAR(20) NOT NULL,
    delivery_address VARCHAR(255) NOT NULL,
    product_amount DECIMAL(10,2) NOT NULL,
    delivery_fee DECIMAL(10,2) NOT NULL,
    total_amount DECIMAL(10,2) NOT NULL,
    order_status TINYINT NOT NULL DEFAULT 0,
    remark VARCHAR(255) DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_admin_test_orders_order_no UNIQUE (order_no)
);

CREATE TABLE order_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    order_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    product_name VARCHAR(100) NOT NULL,
    unit_price DECIMAL(10,2) NOT NULL,
    quantity INT NOT NULL,
    subtotal DECIMAL(10,2) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE admin_account (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR(50) NOT NULL,
    password_hash VARCHAR(100) NOT NULL,
    status TINYINT NOT NULL DEFAULT 1,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_admin_test_admin_username UNIQUE (username)
);
