DROP TABLE IF EXISTS cart_item;
DROP TABLE IF EXISTS product;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
    id BIGINT PRIMARY KEY
);

CREATE TABLE product (
    id BIGINT PRIMARY KEY
);

CREATE TABLE cart_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    quantity INT NOT NULL DEFAULT 1,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_cart_user_product
        UNIQUE (user_id, product_id),
    CONSTRAINT fk_cart_user
        FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_cart_product
        FOREIGN KEY (product_id) REFERENCES product (id)
);

CREATE INDEX idx_cart_user_id
    ON cart_item (user_id);

CREATE INDEX idx_cart_product_id
    ON cart_item (product_id);
