DROP TABLE IF EXISTS user_coupon;
DROP TABLE IF EXISTS coupon;
DROP TABLE IF EXISTS shop;
DROP TABLE IF EXISTS merchant;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR(50) NOT NULL,
    phone VARCHAR(20),
    password_hash VARCHAR(100) NOT NULL,
    nickname VARCHAR(50) NOT NULL,
    gender TINYINT NOT NULL DEFAULT 0,
    avatar_url VARCHAR(255),
    status TINYINT NOT NULL DEFAULT 1,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_coupon_test_user_username UNIQUE (username),
    CONSTRAINT uk_coupon_test_user_phone UNIQUE (phone)
);

CREATE TABLE merchant (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    account VARCHAR(50) NOT NULL,
    password_hash VARCHAR(100) NOT NULL,
    merchant_name VARCHAR(100) NOT NULL,
    contact_name VARCHAR(50) NOT NULL,
    contact_phone VARCHAR(20) NOT NULL,
    status TINYINT NOT NULL DEFAULT 1,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_coupon_test_merchant_account UNIQUE (account)
);

CREATE TABLE shop (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    merchant_id BIGINT NOT NULL,
    shop_name VARCHAR(100) NOT NULL,
    description VARCHAR(255),
    address VARCHAR(255) NOT NULL,
    image_url VARCHAR(255),
    start_price DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    delivery_price DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    business_status TINYINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_coupon_test_shop_merchant
        FOREIGN KEY (merchant_id) REFERENCES merchant (id)
);

CREATE TABLE coupon (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    shop_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    threshold_amount DECIMAL(10,2) NOT NULL,
    discount_amount DECIMAL(10,2) NOT NULL,
    starts_at TIMESTAMP NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    enabled TINYINT NOT NULL DEFAULT 1,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_coupon_test_coupon_shop
        FOREIGN KEY (shop_id) REFERENCES shop (id)
);

CREATE TABLE user_coupon (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    coupon_id BIGINT NOT NULL,
    status TINYINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_coupon_test_user_coupon
        UNIQUE (user_id, coupon_id),
    CONSTRAINT fk_coupon_test_claim_user
        FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_coupon_test_claim_coupon
        FOREIGN KEY (coupon_id) REFERENCES coupon (id)
);