DROP TABLE IF EXISTS delivery_address;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
    id BIGINT PRIMARY KEY
);

CREATE TABLE delivery_address (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    receiver_name VARCHAR(50) NOT NULL,
    receiver_phone VARCHAR(20) NOT NULL,
    address_detail VARCHAR(255) NOT NULL,
    address_label VARCHAR(20) DEFAULT NULL,
    is_default TINYINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_address_user
        FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX idx_address_user_id
    ON delivery_address (user_id);

CREATE INDEX idx_address_user_default
    ON delivery_address (user_id, is_default);
