DROP TABLE IF EXISTS product;
DROP TABLE IF EXISTS product_category;
DROP TABLE IF EXISTS shop;
DROP TABLE IF EXISTS merchant;

CREATE TABLE merchant (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    account VARCHAR(50) NOT NULL,
    password_hash VARCHAR(100) NOT NULL,
    merchant_name VARCHAR(100) NOT NULL,
    contact_name VARCHAR(50) NOT NULL,
    contact_phone VARCHAR(20) NOT NULL,
    status TINYINT NOT NULL DEFAULT 1,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_merchant_product_test_account UNIQUE (account)
);

CREATE TABLE shop (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    merchant_id BIGINT NOT NULL,
    shop_name VARCHAR(100) NOT NULL,
    description VARCHAR(255),
    address VARCHAR(255) NOT NULL,
    image_url VARCHAR(255),
    start_price DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    delivery_price DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    business_status TINYINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_product_test_shop_merchant
        FOREIGN KEY (merchant_id) REFERENCES merchant (id)
);

CREATE TABLE product_category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    shop_id BIGINT NOT NULL,
    category_name VARCHAR(50) NOT NULL,
    sort_order INT NOT NULL DEFAULT 0,
    status TINYINT NOT NULL DEFAULT 1,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_product_test_category_shop_name
        UNIQUE (shop_id, category_name),
    CONSTRAINT fk_product_test_category_shop
        FOREIGN KEY (shop_id) REFERENCES shop (id)
);

CREATE TABLE product (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    shop_id BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    product_name VARCHAR(100) NOT NULL,
    description VARCHAR(255),
    image_url VARCHAR(255),
    price DECIMAL(10,2) NOT NULL,
    stock INT NOT NULL DEFAULT 0,
    status TINYINT NOT NULL DEFAULT 1,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_product_test_product_shop
        FOREIGN KEY (shop_id) REFERENCES shop (id),
    CONSTRAINT fk_product_test_product_category
        FOREIGN KEY (category_id) REFERENCES product_category (id)
);