DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS delivery_address;
DROP TABLE IF EXISTS shop;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
    id BIGINT PRIMARY KEY
);

CREATE TABLE shop (
    id BIGINT PRIMARY KEY
);

CREATE TABLE delivery_address (
    id BIGINT PRIMARY KEY
);

CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    order_no VARCHAR(32) NOT NULL,
    user_id BIGINT NOT NULL,
    shop_id BIGINT NOT NULL,
    address_id BIGINT DEFAULT NULL,
    receiver_name VARCHAR(50) NOT NULL,
    receiver_phone VARCHAR(20) NOT NULL,
    delivery_address VARCHAR(255) NOT NULL,
    product_amount DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    delivery_fee DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    total_amount DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    order_status TINYINT NOT NULL DEFAULT 0,
    remark VARCHAR(255) DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_orders_order_no UNIQUE (order_no),
    CONSTRAINT fk_orders_user
        FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_orders_shop
        FOREIGN KEY (shop_id) REFERENCES shop (id),
    CONSTRAINT fk_orders_address
        FOREIGN KEY (address_id) REFERENCES delivery_address (id)
        ON DELETE SET NULL
);

CREATE INDEX idx_orders_user_status
    ON orders (user_id, order_status);

CREATE INDEX idx_orders_shop_status
    ON orders (shop_id, order_status);

CREATE INDEX idx_orders_address_id
    ON orders (address_id);
