CREATE TABLE coupon (
 id BIGINT PRIMARY KEY, shop_id BIGINT NOT NULL, name VARCHAR(255) NOT NULL,
 threshold_amount DECIMAL(10,2) NOT NULL, discount_amount DECIMAL(10,2) NOT NULL,
 starts_at TIMESTAMP NOT NULL, expires_at TIMESTAMP NOT NULL, enabled TINYINT NOT NULL DEFAULT 1
);
CREATE TABLE user_coupon (
 id BIGINT PRIMARY KEY, user_id BIGINT NOT NULL, coupon_id BIGINT NOT NULL,
 status TINYINT NOT NULL DEFAULT 0, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP
);
ALTER TABLE orders ADD user_coupon_id BIGINT;
ALTER TABLE orders ADD discount_amount DECIMAL(10,2) NOT NULL DEFAULT 0;
