DROP TABLE IF EXISTS product_category;
DROP TABLE IF EXISTS shop;

CREATE TABLE shop (
    id BIGINT PRIMARY KEY
);

CREATE TABLE product_category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    shop_id BIGINT NOT NULL,
    category_name VARCHAR(50) NOT NULL,
    sort_order INT NOT NULL DEFAULT 0,
    status TINYINT NOT NULL DEFAULT 1,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_category_shop_name
        UNIQUE (shop_id, category_name),
    CONSTRAINT fk_category_shop
        FOREIGN KEY (shop_id) REFERENCES shop (id)
);

CREATE INDEX idx_category_shop_id
    ON product_category (shop_id);
