DROP TABLE IF EXISTS product;
DROP TABLE IF EXISTS product_category;
DROP TABLE IF EXISTS shop;

CREATE TABLE shop (
    id BIGINT PRIMARY KEY
);

CREATE TABLE product_category (
    id BIGINT PRIMARY KEY,
    shop_id BIGINT NOT NULL,
    CONSTRAINT fk_product_test_category_shop
        FOREIGN KEY (shop_id) REFERENCES shop (id)
);

CREATE TABLE product (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    shop_id BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    product_name VARCHAR(100) NOT NULL,
    description VARCHAR(255) DEFAULT NULL,
    image_url VARCHAR(255) DEFAULT NULL,
    price DECIMAL(10,2) NOT NULL,
    stock INT NOT NULL DEFAULT 0,
    status TINYINT NOT NULL DEFAULT 1,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_product_shop
        FOREIGN KEY (shop_id) REFERENCES shop (id),
    CONSTRAINT fk_product_category
        FOREIGN KEY (category_id) REFERENCES product_category (id)
);

CREATE INDEX idx_product_shop_id
    ON product (shop_id);

CREATE INDEX idx_product_category_id
    ON product (category_id);

CREATE INDEX idx_product_shop_status
    ON product (shop_id, status);
