DROP TABLE IF EXISTS product;
DROP TABLE IF EXISTS product_category;
DROP TABLE IF EXISTS shop;

CREATE TABLE shop (
    id BIGINT PRIMARY KEY
);

CREATE TABLE product_category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    shop_id BIGINT NOT NULL,
    category_name VARCHAR(50) NOT NULL,
    sort_order INT NOT NULL DEFAULT 0,
    status TINYINT NOT NULL DEFAULT 1,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uk_public_product_category_shop_name
        UNIQUE (shop_id, category_name),
    CONSTRAINT fk_public_product_category_shop
        FOREIGN KEY (shop_id) REFERENCES shop (id)
);

CREATE TABLE product (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    shop_id BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    product_name VARCHAR(100) NOT NULL,
    description VARCHAR(255),
    image_url VARCHAR(255),
    price DECIMAL(10,2) NOT NULL,
    stock INT NOT NULL DEFAULT 0,
    status TINYINT NOT NULL DEFAULT 1,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT fk_public_product_shop
        FOREIGN KEY (shop_id) REFERENCES shop (id),
    CONSTRAINT fk_public_product_category
        FOREIGN KEY (category_id) REFERENCES product_category (id)
);