DROP TABLE IF EXISTS shop;
DROP TABLE IF EXISTS merchant;

CREATE TABLE merchant (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    account VARCHAR(50) NOT NULL,
    password_hash VARCHAR(100) NOT NULL,
    merchant_name VARCHAR(100) NOT NULL,
    contact_name VARCHAR(50) NOT NULL,
    contact_phone VARCHAR(20) NOT NULL,
    status TINYINT NOT NULL DEFAULT 1,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_shop_test_merchant_account UNIQUE (account)
);

CREATE TABLE shop (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    merchant_id BIGINT NOT NULL,
    shop_name VARCHAR(100) NOT NULL,
    description VARCHAR(255) DEFAULT NULL,
    address VARCHAR(255) NOT NULL,
    image_url VARCHAR(255) DEFAULT NULL,
    start_price DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    delivery_price DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    business_status TINYINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_shop_merchant
        FOREIGN KEY (merchant_id) REFERENCES merchant (id)
);

CREATE INDEX idx_shop_merchant_id ON shop (merchant_id);
